name = "mainloop-frontend"
compatibility_date = "2025-12-17"
main = ".svelte-kit/cloudflare/_worker.js"

[assets]
directory = ".svelte-kit/cloudflare"
binding = "ASSETS"

[env.production]
name = "mainloop-frontend"
route = { pattern = "mainloop.olds.network", zone_name = "olds.network" }
