apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mainloop

resources:
  - namespace.yaml
  - deployment-backend.yaml
  - deployment-claude-agent.yaml
  - service-backend.yaml
  - configmap.yaml
  - cloudflared.yaml
