apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mainloop

resources:
  - namespace.yaml
  - rbac-backend.yaml
  - networkpolicy.yaml
  - pvc-repo-cache.yaml
  - deployment-backend.yaml
  - deployment-agent-controller.yaml
  - deployment-frontend.yaml
  - service-backend.yaml
  - service-frontend.yaml
  - service-agent-controller.yaml
  - configmap.yaml
