apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: mainloop-secrets
  namespace: mainloop
spec:
  itemPath: vaults/kubernetes/items/mainloop-secrets
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: cloudflared-credentials
  namespace: mainloop
spec:
  itemPath: vaults/kubernetes/items/cloudflared-mainloop
